# Building my own actions workflow
# To check the python installation

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.7']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python and Platform version
        run: python -c "import sys; print(sys.version); print(sys.platform)"
      - name: Install dependencies simple check
        run: |
          python -m pip install --user --upgrade build
          pip install pytest
          pip install .
          python simple_test.py
      - name: Run tests with pytest
        run: pytest 
      - run: echo "🍏 This job's status is ${{ job.status }}."


# Maybe generate an artifact for the readme?